### ISSUE TITLE
Firefox 36 has HTTP/2 enabled by default, but your page tells me otherwise

### ISSUE THREAD

**Issue by flying-sheep** [bradfitz/http2#29]
Going to https://http2.golang.org/ i see:

> Unfortunately, you're **not** using HTTP/2 right now

but ff 36 undoubtedly does.

**Comment by bradfitz** [comment]
Yup. http2.golang.org hasn't been redeployed since HTTP/2 was finalized and thus had its ALPN protocol name change.

So you in fact are not using HTTP/2 when it says that, because Firefox is advertising "h2" and the server is advertising "h2-14" or whatever.

**Comment by nathany** [comment]
> Congratulations, you're using HTTP/2 right now.

It works now. :-)

**Comment by flying-sheep** [comment]
> So you in fact are not using HTTP/2 when it says that, because Firefox is advertising "h2" and the server is advertising "h2-14" or whatever.

sure, got that, but that’s the server’s outdatedness, not firefox’ :)

> It works now. :-)

not for me :(

**Comment by bradfitz** [comment]
I've re-deployed http2.golang.org with the latest version of the Go server package which advertises "h2".

But it seems that even Firefox 36.0.1 only sends "h2" if you have "network.http.spdy.enabled.http2draft" (note the "draft" suffix) enabled, despite "h2" no longer being a draft version.

I'm closing this bug, since I verified in Firefox 36.0.1 that I see `NegotiatedProtocol:"h2"` at https://http2.golang.org/reqinfo and "h2" is the final version (as opposed to "h2-14", which we also still advertise).

**Comment by flying-sheep** [comment]
i’m using firefox 36.0.1 and see:

```http
Method: GET
Protocol: HTTP/1.1
Host: http2.golang.org
RemoteAddr: 146.107.110.230:53612
RequestURI: "/reqinfo"
URL: &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/reqinfo", RawQuery:"", Fragment:""}
Body.ContentLength: 0 (-1 means unknown)
Close: false (relevant for HTTP/1 only)
TLS: &tls.ConnectionState{Version:0x301, HandshakeComplete:true, DidResume:false, CipherSuite:0xc013, NegotiatedProtocol:"", NegotiatedProtocolIsMutual:true, ServerName:"http2.golang.org", PeerCertificates:[]*x509.Certificate(nil), VerifiedChains:[][]*x509.Certificate(nil), TLSUnique:[]uint8{0xd0, 0xf8, 0x20, 0xa3, 0xc7, 0x17, 0xac, 0x33, 0xb7, 0x7a, 0xff, 0xec}}

Headers:
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Dnt: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
```

**Comment by bgentry** [comment]
@flying-sheep I just tried this using Firefox 36.0.1 on OS X and got HTTP2:

```
Method: GET
Protocol: HTTP/2.0
Host: http2.golang.org
RemoteAddr: 73.162.123.157:49552
RequestURI: "/reqinfo"
URL: &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/reqinfo", RawQuery:"", Fragment:""}
Body.ContentLength: 0 (-1 means unknown)
Close: false (relevant for HTTP/1 only)
TLS: &tls.ConnectionState{Version:0x303, HandshakeComplete:true, DidResume:false, CipherSuite:0xc02f, NegotiatedProtocol:"h2", NegotiatedProtocolIsMutual:true, ServerName:"http2.golang.org", PeerCertificates:[]*x509.Certificate(nil), VerifiedChains:[][]*x509.Certificate(nil), TLSUnique:[]uint8{0xbb, 0x10, 0x59, 0x2d, 0x37, 0x1f, 0xca, 0x1d, 0x5d, 0xc, 0x8d, 0x90}}

Headers:
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Referer: https://http2.golang.org/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0
```

But it turned out that I did have the setting `network.http.spdy.enabled.http2draft` enabled in `about:config`. Turning it off gives me an HTTP/1.1 page. You should toggle that setting or wait for a future Firefox update which will probably rely on `network.http.spdy.enabled.http2` instead (which looks to be enabled-by-default)

**Comment by flying-sheep** [comment]
all `network.http.spdy.enabled.*` settings are `true` for me.

**Comment by nathany** [comment]
Could it be some sort of caching issue or intermediate proxy? I suspect not, but throwing it out there. 

What OS?

**Comment by flying-sheep** [comment]
nope, no proxy, VPN, …

linux.

**Comment by porjo** [comment]
> linux.

@flying-sheep  which distro? I'm using Firefox 36.0 on Fedora 21 and I see 'Congratulations, you're using HTTP/2 right now'. Using Firefox developer tools I see the following Response headers:

```
Content-Length: 1576
Content-Type: text/html; charset=utf-8
X-Firefox-Spdy: h2
```

AFAIK all my Firefox settings are set to defaults.

**Comment by flying-sheep** [comment]
arch. and firefox developer edition (38) works well…
