### ISSUE TITLE
tls: oversized record received with length 20527

### ISSUE THREAD

**Issue by xyproto** [bradfitz/http2#32]
Hi,

This is more a support request than a bug report.

I'm trying to give HTTP/2 a spin, so I wrote a small server and client in Go, using the http2 package.
However, when connecting to my local server, I get errors when connecting over https://:

`tls: oversized record received with length 20527`

And also when connecting over http://:

`http2: unsupported scheme and no Fallback`

Steps to reproduce:
1. Install and run [github.com/xyproto/snupibupi](https://github.com/xyproto/snupibupi)
(will listen to port 3000 on localhost).
2. Install [github.com/xyproto/http2check](https://github.com/xyproto/http2check).
3. Run `http2check https://localhost:3000` and `http2check http://localhost:3000`

There is not necessarily anything wrong with the results so far.

The question is as follows:

How can I use the http2 package locally, for setting up both a server and client for HTTP/2? Does it require going through fire and water, buying a commercial https certificate or creating a self signed one, and wrapping it all in a webserver like nginx? Or is there an easier way?

Best regards,
Alexander F Rødseth

**Comment by SlyMarbo** [comment]
`github.com/xyproto/snupibupi` is using `http.ListenAndServe`, not `http.ListenAndServeTLS`, so it's trying to use HTTP, which won't work.

**Comment by xyproto** [comment]
Thank you! Will try that.

**Comment by xyproto** [comment]
Using ListenAndServeTLS and self signed certificates did the trick, thanks.
