### ISSUE TITLE
Non HTTPS HTTP/2

### ISSUE THREAD

**Issue by kidoman** [bradfitz/http2#37]
While I understand the rationale of only supporting HTTP/2 over HTTPS (similar to why wss: is more advisable vs ws:) how does this affect the ability to front Go based HTTP/2 servers with nginx/AWS ELB/etc. We could choose to do this for simply not having to manage SSL termination in our Go application code.

In that situation, the HTTP/2 traffic to nginx (for example) would need to them downgrade to HTTP because no one uses HTTPS for internal traffic (at least a majority of installations don't.)

**Comment by brk0v** [comment]
Hi,

From my point of view there is no considerable improvement of using http/2  between load balancer and  backends. As usual we have low latency and small amount of packets lost here. So downgrading to http is not an issue imo.

**Comment by bradfitz** [comment]
Yeah, the network is usually fine between your frontend and backends. HTTP/1.1 or even HTTP/1.0 works if you're concerned about the crypto overhead. Or you could use TLS in a non-encrypting mode, with tweaks on the server & client config to permit that.

It's true we won't be supporting non-HTTPS HTTP/2 in this package, but it's possible we'll provide hooks for people to do non-HTTPS HTTP/2 within a datacenter.

Closing this as there's nothing in particular to do, at least yet.

**Comment by kidoman** [comment]
Since grpc-go is using this package for providing HTTP/2 support, I am assuming a lot of people are going to be using it to talk amongst services running in the same datacenter.

Thanks for the alternatives you mentioned though.
