### ISSUE TITLE
readFrames leaks goroutines on serve loop exit

### ISSUE THREAD

**Issue by pabbott0** [bradfitz/http2#46]
Once again, I already have a fix, just need to write a test.

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo if still relevant or desired. Thanks!
