### ISSUE TITLE
server push (from the server side)

### ISSUE THREAD

**Issue by jmhodges** [bradfitz/http2#51]
Some systems, like jetty, are considering implementing hooks where HTTP/1 responses sent back with specially formatted Link headers are turned into requests that are sent to the client and back into the server.

Another idea is making the ResponseWriter passed in to ServeHTTP be convertible to some kind of PushWriter that will take request headers and, some time later, responses.

One more idea is to allow the user access to the Framer or similar interface (perhaps through the ResponseWriter or by them implementing a different interface than http.Handler), and let them do the dirty work if they want it.

**Comment by brk0v** [comment]
Hi, 

Please take a look at this pool request https://github.com/bradfitz/http2/pull/34. In the code of demo server you can find example of a push handler.

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo if still relevant or desired. Thanks!
