### ISSUE TITLE
Denial of Service Protection

### ISSUE THREAD

**Issue by tav** [bradfitz/http2#52]
Thanks for the great work @bradfitz. I was thinking of going through the code and figuring out what DoS protection measures still need to be added — like I did with the `net/http` package [back in 2011](https://github.com/golang/go/issues/2093). Is this something that would be useful or have you already got this figured out?

**Comment by abursavich** [comment]
Sensible [limits on header block size](https://http2.github.io/http2-spec/#rfc.section.10.5.1) is at the top of my most wanted list.

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo if still relevant or desired. Thanks!
