### ISSUE TITLE
HTTP/2 is working with TLS `MaxVersion: tls.VersionTLS11`

### ISSUE THREAD

**Issue by jansauer** [bradfitz/http2#66]
It shouldn't be possible to create a working HTTP/2 server with TLS 1.1.

[HTTP/2 RFC 7540](https://tools.ietf.org/html/rfc7540):
```
9.2.  Use of TLS Features
   Implementations of HTTP/2 MUST use TLS version 1.2 [TLS12] or higher
   for HTTP/2 over TLS.
````

Example code should fail:
```go
package main

import (
	"crypto/tls"
	"github.com/bradfitz/http2"
	"io"
	"net/http"
)

const (
	TLS_PRIVATE_KEY = "localhost.dev.key"
	TLS_PUBLIC_KEY  = "localhost.dev.crt"
)

func handle(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, "Hello world!")
}

func main() {
	http.HandleFunc("/", handle)
	config := &tls.Config{
		MinVersion: tls.VersionTLS11,
		MaxVersion: tls.VersionTLS11,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
		},
		PreferServerCipherSuites: true,
	}
	server := &http.Server{Addr: ":4000", Handler: nil, TLSConfig: config}
	http2.ConfigureServer(server, nil)
	server.ListenAndServeTLS(TLS_PUBLIC_KEY, TLS_PRIVATE_KEY)
}
```

**Comment by mdlayher** [comment]
It appears that this is the expected behavior: https://github.com/bradfitz/http2/blob/master/server.go#L144-L149.

**Comment by jansauer** [comment]
I never thought about if it should be the job of the server or the client to enforce this role.

The note however is referring to MinVersion. Having the TLS 1.2 HTTP/2 part not interfere with HTTP/1.1 traffic makes sense. Wouldn't `MaxVersion: tls.VersionTLS11` make the the HTTP/2 useless?

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo if still relevant or desired. Thanks!
