### ISSUE TITLE
This lib still alive ?!

### ISSUE THREAD

**Issue by sintanial** [bradfitz/http2#76]
This repository still alive ? Recent changes have been 4 months ago! Can it be used in the project!? I need http2 protocol implementation on go and java(for android). But on this page https://github.com/http2/http2-spec/wiki/Implementations for golang only one library, and it's this library !! And I was confused by the fact that it is still in development. Has anyone already tried it!?

**Comment by bradfitz** [comment]
You can use the server. People already do. The client is still in development. They should both be included in Go 1.6. That's the plan.
