### ISSUE TITLE
status? no updates since May

### ISSUE THREAD

**Issue by glycerine** [bradfitz/http2#77]
Just wondering how the http2 client (and server, for that matter) work is coming-- there haven't been any commits to this repo since May.

Comments on usability at this point?

Thanks.

**Comment by bradfitz** [comment]
I've been distracted. Dup of #76

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.
