### ISSUE TITLE
outline of client work remaining

### ISSUE THREAD

**Issue by glycerine** [bradfitz/http2#78]
Depending on the scope and nature of work left to do on the client, I may be able to contribute.

Could someone outline what needs to be done?  Hopefully describe the TODOs in enough detail that we might be able to file reasonable pull requests.

Thanks!

Jason

**Comment by bradfitz** [comment]
Honestly I just need to sit down and do it. That will be easier than explaining it and doing code reviews. I know that's not very helpful, though.
