### ISSUE TITLE
port number in SNI

### ISSUE THREAD

**Issue by icing** [bradfitz/http2#80]
With

```
h2i test.example.org:12346
```

the SNI is sent as ```test.example.org:12346``` which is not correct and makes my Apache httpd virtual host selection fail.

**Comment by bradfitz** [comment]
This repo is shut down. Please file a bug as described in the README:

https://github.com/bradfitz/http2/blob/master/README

> Bugs should be filed in Go's main bug tracker:
>
>    https://github.com/golang/go/issues/new?title=x/net/http2:+
