### ISSUE TITLE
https://http2.golang.org pointing to this repo and needs updating

### ISSUE THREAD

**Issue by eosrei** [bradfitz/http2#81]
*Not sure if this is the ideal location to address this issue, but it'll work. Direct me elsewhere as needed.*

https://http2.golang.org and this repo are still tops hit on searches for "go http2". The text:

> The code is currently at github.com/bradfitz/http2 but will move to the Go standard library at some point in the future (enabled by default, without users needing to change their code).

If both pages linked directly to: https://godoc.org/golang.org/x/net/http2 (or ???) it would reduce the confusion causing the other recent github issues in this repo.

**Comment by bradfitz** [comment]
Done.
